name: Lint PR

on:
  pull_request:
    branches: — main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install linter
        run: apt-get install -y golint

      - name: Run vet & lint
        run: |
          go vet .
          golint .
